### ISSUE TITLE
can run_server work together with gunicorn?

### ISSUE THREAD

**Issue by sylvoslee** [idom-team/idom-dash#7]
I used to deploy dash like this：
```
gunicorn -w 4 -b 0.0.0.0:80 main:server
```

**Comment by rmorshea** [comment]
If `gunicorn` supports web sockets, then yes. You'll also want to use `app.run_server` instead of `idom_dash.run_server`.

The only reason I need `idom_dash.run_server` is because the dev server for Flask doesn't support web sockets so I have to use `pywsgi` instead of `werkzueg`.

**Comment by rmorshea** [comment]
Looks like `gunicorn` supports web sockets? The Flask extension I'm using under the hood shows how to use it in its documentation: https://github.com/heroku-python/flask-sockets#deployment

**Comment by rmorshea** [comment]
Let me know if that works.

**Comment by rmorshea** [comment]
Crap. #8 actually closes #6
